# Generated by Django 3.2 on 2021-04-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_serv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='group',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='uid',
        ),
    ]
